### ISSUE TITLE
image_viewer SAR image protobuf writer is broken

### ISSUE THREAD

**Issue by griffinfoster** [ZendarInc/ZendarSDK#23]
It seems with the recent changes to protobuf definition locations that the SAR image protobuf writer in image_viewer.py is broken. I get the following error:

```Process Process-1:
Process Process-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gfoster/ZendarSDK/python/viewer/image_viewer.py", line 216, in visualize_single_radar
    proto_writer.write(proto_out)
  File "/home/gfoster/ZendarSDK/python/viewer/radar_data_streamer.py", line 79, in write
    serial = record.SerializeToString()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
google.protobuf.message.EncodeError: Message zen_proto.data.Image is missing required fields: cartesian.data.type
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gfoster/ZendarSDK/python/viewer/image_viewer.py", line 216, in visualize_single_radar
    proto_writer.write(proto_out)
  File "/home/gfoster/ZendarSDK/python/viewer/radar_data_streamer.py", line 79, in write
    serial = record.SerializeToString()
google.protobuf.message.EncodeError: Message zen_proto.data.Image is missing required fields: cartesian.data.type
merging video ...
[swscaler @ 0x55a96ef2c960] Warning: data is not aligned! This can lead to a speed loss
Traceback (most recent call last):
  File "/home/gfoster/ZendarSDK/python/viewer/image_viewer.py", line 448, in <module>
    main()
  File "/home/gfoster/ZendarSDK/python/viewer/image_viewer.py", line 129, in main
    combined_frame = cv2.cvtColor(combined_frame, cv2.COLOR_BGR2RGB)
TypeError: Expected Ptr<cv::UMat> for argument '%s```

Commenting out `proto_writer.write(proto_out)` skips over the writing to protobuf to allow videos to be generated.

**Comment by jimmy-zendar** [comment]
@ghsyu would know this more than I do.
